#!/usr/bin/env bash

printf "\e[33;1m%s\e[0m\n" 'Running the Flutter analyzer'

flutter analyze
if [ $? -ne 0 ]; then
    printf "\e[33;1m%s\e[0m\n" 'Flutter analyzer error'
    exit 1;
fi

printf "\e[33;1m%s\e[0m\n" 'Flutter analyzer finished'

printf "\e[33;1m%s\e[0m\n" 'Running Flutter tests'

flutter test
if [ $? -ne 0 ]; then
    printf "\e[33;1m%s\e[0m\n" 'Flutter test error'
    exit 1
fi

printf "\e[33;1m%s\e[0m\n" 'Flutter tests finished'